version: '3.8'
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    restart: unless-stopped
